plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

android {
  namespace "com.appcuescustompreviewer"

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 35)
    versionName "1.0.0"
    versionCode 1
  }
}

dependencies {
  implementation "com.appcues:appcues:3+"
}

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
